In [3]:
import torch

torch.cuda.is_available()

True

# 버전 확인

In [4]:
torch.__version__

'2.8.0+cu126'

# tensor 데이터 생성

In [5]:
torch.tensor(5)

tensor(5)

In [6]:
torch.tensor([1, 2, 3])

tensor([1, 2, 3])

In [7]:
torch.tensor([[1, 2, 3], [4, 5, 6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [8]:
data = [1,2, 3, 4, 5]
torch.tensor(data)

tensor([1, 2, 3, 4, 5])

In [9]:
import numpy as np
data = np.array([1,2,3,4,5])
torch.tensor(data)

tensor([1, 2, 3, 4, 5])

In [10]:
torch.ones(3)

tensor([1., 1., 1.])

In [11]:
torch.ones((2, 2))

tensor([[1., 1.],
        [1., 1.]])

In [12]:
torch.ones((512, 512)) # 이미지 흰색

tensor([[1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.],
        ...,
        [1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.]])

In [13]:
torch.zeros((512, 512)) # 이미지 검정색

tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])

In [14]:
torch.eye(5) # 단위 행렬

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [15]:
torch.arange(1, 10)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
torch.arange(1, 10, 2)

tensor([1, 3, 5, 7, 9])

In [17]:
torch.rand(5)

tensor([0.7007, 0.5700, 0.9268, 0.3306, 0.2668])

# tensor 차원 변경

In [18]:
data = torch.rand(3, 3, 3)
data

tensor([[[0.9054, 0.6069, 0.7107],
         [0.3082, 0.7712, 0.4765],
         [0.7245, 0.3763, 0.3814]],

        [[0.9966, 0.2781, 0.7850],
         [0.6615, 0.3447, 0.3785],
         [0.4121, 0.1556, 0.9162]],

        [[0.4732, 0.0150, 0.5975],
         [0.7355, 0.7278, 0.5817],
         [0.3785, 0.9067, 0.4407]]])

In [19]:
data.view((9, 3))

tensor([[0.9054, 0.6069, 0.7107],
        [0.3082, 0.7712, 0.4765],
        [0.7245, 0.3763, 0.3814],
        [0.9966, 0.2781, 0.7850],
        [0.6615, 0.3447, 0.3785],
        [0.4121, 0.1556, 0.9162],
        [0.4732, 0.0150, 0.5975],
        [0.7355, 0.7278, 0.5817],
        [0.3785, 0.9067, 0.4407]])

In [20]:
data.view(27) # 1차원으로 flatten

tensor([0.9054, 0.6069, 0.7107, 0.3082, 0.7712, 0.4765, 0.7245, 0.3763, 0.3814,
        0.9966, 0.2781, 0.7850, 0.6615, 0.3447, 0.3785, 0.4121, 0.1556, 0.9162,
        0.4732, 0.0150, 0.5975, 0.7355, 0.7278, 0.5817, 0.3785, 0.9067, 0.4407])

In [21]:
data.view(-1) # 1차원으로 flatten

tensor([0.9054, 0.6069, 0.7107, 0.3082, 0.7712, 0.4765, 0.7245, 0.3763, 0.3814,
        0.9966, 0.2781, 0.7850, 0.6615, 0.3447, 0.3785, 0.4121, 0.1556, 0.9162,
        0.4732, 0.0150, 0.5975, 0.7355, 0.7278, 0.5817, 0.3785, 0.9067, 0.4407])

In [22]:
data.view(3, -1) # 행의 값을 3으로 하고 열의 값을 알아서 채워줌

tensor([[0.9054, 0.6069, 0.7107, 0.3082, 0.7712, 0.4765, 0.7245, 0.3763, 0.3814],
        [0.9966, 0.2781, 0.7850, 0.6615, 0.3447, 0.3785, 0.4121, 0.1556, 0.9162],
        [0.4732, 0.0150, 0.5975, 0.7355, 0.7278, 0.5817, 0.3785, 0.9067, 0.4407]])

In [23]:
data.view(-1,3)

tensor([[0.9054, 0.6069, 0.7107],
        [0.3082, 0.7712, 0.4765],
        [0.7245, 0.3763, 0.3814],
        [0.9966, 0.2781, 0.7850],
        [0.6615, 0.3447, 0.3785],
        [0.4121, 0.1556, 0.9162],
        [0.4732, 0.0150, 0.5975],
        [0.7355, 0.7278, 0.5817],
        [0.3785, 0.9067, 0.4407]])

# tensor 데이터의 형태 확인

In [24]:
data.shape

torch.Size([3, 3, 3])

In [25]:
data.dtype

torch.float32

In [26]:
data.dim()

3

# cuda 디바이스 체크 및 데이터 올리기

In [27]:
torch.cuda.get_device_name(0)

'NVIDIA GeForce RTX 4070 Laptop GPU'

In [29]:
device = torch.device("cuda:1")

In [ ]:
data = torch.tensor([1, 2, 3]) # 현재는 GPU가 아닌 CPU 메모리에 올라와 있는 상태
data

tensor([1, 2, 3])

In [ ]:
data.to('cuda') # 데이터를 GPU로 올리기 1 

tensor([1, 2, 3], device='cuda:0')

In [35]:
data1 = torch.tensor([1,2,3]).cuda() # 데이터를 GPU로 올리기 2

In [36]:
data1.to('cpu')

tensor([1, 2, 3])

# tensor 연산

In [ ]:
data = data.to('cuda')
data1 = torch.tensor([1,2,3]).cuda()

tensor([2, 4, 6], device='cuda:0')

In [38]:
data + data1

tensor([2, 4, 6], device='cuda:0')

In [39]:
data - data1

tensor([0, 0, 0], device='cuda:0')

In [40]:
data / data1

tensor([1., 1., 1.], device='cuda:0')

In [41]:
data * data1

tensor([1, 4, 9], device='cuda:0')

# tensor 내장 함수

In [45]:
data = torch.tensor([[1, 2, 3], [4, 5, 6]])

In [46]:
data.min()

tensor(1)

In [48]:
data.min(dim = 0)

torch.return_types.min(
values=tensor([1, 2, 3]),
indices=tensor([0, 0, 0]))

In [49]:
data.max(dim = 1)

torch.return_types.max(
values=tensor([3, 6]),
indices=tensor([2, 2]))

In [51]:
print(data.dtype)
data = data.type(torch.float)
print(data.dtype)

torch.int64
torch.float32


In [ ]:
data1 = torch.tensor([[1, 2, 3], [4, 5, 6]])
data2 = torch.tensor([[1.5, 2.5, 3.5], [4.5, 5.5, 6.5]])
data1 + data2

# data 의 타입이 정수형으로 형변환 되었다...

# 예시 : 이미지 처리

In [ ]:
image = torch.rand(3, 128, 128)
image.view(1, 3, 128, 128).shape # 이미지 차원 변경 1

torch.Size([1, 3, 128, 128])

In [64]:
image = torch.rand(3, 128, 128)
image = image.unsqueeze(dim=0)  # 이미지 차원 변경 2
# 지정한 위치에 차원을 늘려주는 역할
image.shape

torch.Size([1, 3, 128, 128])

In [77]:
image = torch.rand(1, 128, 128)
image = image.squeeze(dim=0)
image.shape

torch.Size([128, 128])